branch-defaults:
  default:
    environment: DayPlanner-env
    group_suffix: null
global:
  application_name: DayPlanner
  branch: null
  default_ec2_keyname: dayplanner
  default_platform: Python 2.7
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
