# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('startingTime', models.TimeField(default=None)),
                ('endTime', models.TimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='123 Ave', max_length=100)),
                ('cellphone', models.CharField(default='XXX-XXX-XXX', max_length=12)),
                ('homephone', models.CharField(default='XXX-XXX-XXX', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='TimeClock',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('signIn', models.DateTimeField()),
                ('signOut', models.DateTimeField()),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DayPlanner.Profile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Store')),
            ],
            bases=('DayPlanner.profile',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DayPlanner.Profile')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Franchise')),
            ],
            bases=('DayPlanner.profile',),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Employee'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Employee'),
        ),
    ]
