# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('startingTime', models.TimeField(default=None)),
                ('endTime', models.TimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('cellnumber', models.CharField(blank=True, max_length=12)),
                ('relationship', models.CharField(blank=True, max_length=12)),
                ('homenumber', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('cellnumber', models.CharField(blank=True, max_length=12)),
                ('homenumber', models.CharField(blank=True, max_length=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical profile',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('cellnumber', models.CharField(blank=True, max_length=12)),
                ('homenumber', models.CharField(blank=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(default=None)),
                ('employee', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='TimeClock',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('signIn', models.DateTimeField()),
                ('signOut', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Employee')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Store')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Profile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Profile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Store'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Profile'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayPlanner.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='dayschedule',
            unique_together=set([('employee', 'date')]),
        ),
    ]
