# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayPlanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='content',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='request',
            name='shifts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
