# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cellphone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='homephone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='dayschedule',
            unique_together=set([('employee', 'date')]),
        ),
    ]
