# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DayPlanner', '0002_auto_20170617_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='location',
        ),
    ]
