# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayPlanner', '0002_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
