# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DayPlanner', '0003_emergencycontact_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='relation',
            new_name='relationship',
        ),
    ]
